# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(771, 506)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.get_file1 = QtWidgets.QPushButton(self.centralwidget)
        self.get_file1.setGeometry(QtCore.QRect(610, 30, 101, 41))
        self.get_file1.setObjectName("get_file1")
        self.get_file2 = QtWidgets.QPushButton(self.centralwidget)
        self.get_file2.setGeometry(QtCore.QRect(610, 90, 101, 41))
        self.get_file2.setObjectName("get_file2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 80, 141, 41))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 20, 141, 41))
        self.label_2.setObjectName("label_2")
        self.file_path1 = QtWidgets.QLineEdit(self.centralwidget)
        self.file_path1.setGeometry(QtCore.QRect(170, 30, 431, 41))
        self.file_path1.setObjectName("file_path1")
        self.file_path2 = QtWidgets.QLineEdit(self.centralwidget)
        self.file_path2.setGeometry(QtCore.QRect(170, 90, 431, 41))
        self.file_path2.setObjectName("file_path2")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(40, 240, 671, 251))
        self.textEdit.setObjectName("textEdit")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 200, 141, 41))
        self.label_3.setObjectName("label_3")
        self.subit = QtWidgets.QPushButton(self.centralwidget)
        self.subit.setGeometry(QtCore.QRect(310, 160, 111, 41))
        self.subit.setObjectName("subit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.get_file1.setText(_translate("MainWindow", "select file"))
        self.get_file2.setText(_translate("MainWindow", "select file"))
        self.label.setText(_translate("MainWindow", "Choose .py file 2"))
        self.label_2.setText(_translate("MainWindow", "Choose .py file 1"))
        self.label_3.setText(_translate("MainWindow", "Assessment Result"))
        self.subit.setText(_translate("MainWindow", "Submit"))
